from abc import ABC, abstractmethod

from src.domain.entities.time_schema import TimeCreate, TimeOut


class ITimeRepository(ABC):
    @abstractmethod
    async def list_all(self) -> list[TimeOut]: ...
    @abstractmethod
    async def get_by_id(self, time_id: int) -> TimeOut | None: ...
    @abstractmethod
    async def create(self, data: TimeCreate) -> TimeOut: ...
    @abstractmethod
    async def update(self, time_id: int, data: TimeCreate) -> TimeOut: ...
    @abstractmethod
    async def delete(self, time_id: int) -> None: ...
    @abstractmethod
    async def get_by_coo(self, coo_id: int) -> list[TimeOut]: ...
    @abstractmethod
    async def get_by_gerente(self, gerente_id: int) -> list[TimeOut]: ...
    @abstractmethod
    def get_by_name(self, name: str) -> TimeOut | None: ...
    @abstractmethod
    async def list_by_user_id(self, user_id: int) -> list[TimeOut]: ...
