from abc import ABC, abstractmethod
from typing import Optional, List

from src.domain.entities.time_schema import TimeOut, TimeCreate


class ITimeRepository(ABC):
    @abstractmethod
    async def list_all(self) -> List[TimeOut]: ...
    @abstractmethod
    async def get_by_id(self, time_id: int) -> Optional[TimeOut]: ...
    @abstractmethod
    async def create(self, data: TimeCreate) -> TimeOut: ...
    @abstractmethod
    async def update(self, time_id: int, data: TimeCreate) -> TimeOut: ...
    @abstractmethod
    async def delete(self, time_id: int) -> None: ...
    @abstractmethod
    async def get_by_coo(self, coo_id: int) -> List[TimeOut]: ...
    @abstractmethod
    async def get_by_gerente(self, gerente_id: int) -> List[TimeOut]: ...
    @abstractmethod
    def get_by_name(self, name: str) -> Optional[TimeOut]: ...
